In [1]:
import numpy as np

In [5]:
s = np.array(5)
print(s.shape)
x = s + 3
print(x)

()
8


In [6]:
v = np.array([1,2,3])
print(v.shape)

(3,)


In [7]:
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5
    
print(values)

[6, 7, 8, 9, 10]


In [9]:
values = [1,2,3,4,5]
values = np.array(values) + 5

print(values)

[ 6  7  8  9 10]


In [11]:
a = np.array([[1,3],[5,7]])
a

b = np.array([[2,4],[6,8]])
b

a + b

array([[ 3,  7],
       [11, 15]])

In [12]:
c = np.array([[2,3,6],[4,5,9],[1,8,7]])
c
# exibe o seguinte resultado:
# array([[2, 3, 6],
#        [4, 5, 9],
#        [1, 8, 7]])

print(a.shape)
# exibe o seguinte resultado:
#  (2, 2)

print(c.shape)
# exibe o seguinte resultado:
#  (3, 3)

(2, 2)
(3, 3)


In [15]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a
# exibe o seguinte resultado:
# array([[1, 2, 3, 4],
#        [5, 6, 7, 8]])
a.shape
# exibe o seguinte resultado:
# (2, 4)

b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b
# exibe o seguinte resultado:
# array([[ 1,  2,  3],
#        [ 4,  5,  6],
#        [ 7,  8,  9],
#        [10, 11, 12]])
b.shape
# exibe o seguinte resultado:
# (4, 3)

c = np.matmul(a, b)
print(c)
# exibe o seguinte resultado:
# array([[ 70,  80,  90],
#        [158, 184, 210]])
c.shape
# exibe o seguinte resultado:
# (2, 3)

[[ 70  80  90]
 [158 184 210]]


(2, 3)

In [16]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m
# exibe o seguinte resultado:
# array([[ 1,  2,  3,  4],
#        [ 5,  6,  7,  8],
#        [ 9, 10, 11, 12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [18]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
inputs
# exibe o seguinte resultado:
# array([[-0.27,  0.45,  0.64,  0.31]])

array([[-0.27,  0.45,  0.64,  0.31]])

In [19]:
inputs.shape

(1, 4)

In [20]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

In [21]:
weights.shape

(3, 4)

In [23]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

In [1]:
import pandas as pd

# TODO: Set weight1, weight2, and bias
weight1 = 1.1
weight2 = 1.1
bias = -2.0


# DON'T CHANGE ANYTHING BELOW
# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [False, False, False, True]
outputs = []

# Generate and check output
for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = int(linear_combination >= 0)
    is_correct_string = 'Yes' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', '  Linear Combination', '  Activation Output', '  Is Correct'])
if not num_wrong:
    print('Nice!  You got it all correct.\n')
else:
    print('You got {} wrong.  Keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))




Nice!  You got it all correct.

Input 1    Input 2    Linear Combination    Activation Output   Is Correct
      0          0                  -2.0                    0          Yes
      0          1                  -0.9                    0          Yes
      1          0                  -0.9                    0          Yes
      1          1                   0.2                    1          Yes


In [2]:
# GRADIENT DESCENT

import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

def sigmoid_prime(x):
    """
    # Derivative of the sigmoid function
    """
    return sigmoid(x) * (1 - sigmoid(x))

learnrate = 0.5
x = np.array([1, 2, 3, 4])
y = np.array(0.5)

# Initial weights
w = np.array([0.5, -0.5, 0.3, 0.1])

### Calculate one gradient descent step for each weight
### Note: Some steps have been consilated, so there are
###       fewer variable names than in the above sample code

# TODO: Calculate the node's linear combination of inputs and weights
h = np.dot(x,w)

# TODO: Calculate output of neural network
nn_output = sigmoid(h)

# TODO: Calculate error of neural network
error = y - nn_output

# TODO: Calculate the error term
#       Remember, this requires the output gradient, which we haven't
#       specifically added a variable for.
error_term = error * sigmoid_prime(h)

# TODO: Calculate change in weights
del_w = learnrate * error_term * x

print('Neural Network output:')
print(nn_output)
print('Amount of Error:')
print(error)
print('Change in Weights:')
print(del_w)

Neural Network output:
0.689974481128
Amount of Error:
-0.189974481128
Change in Weights:
[-0.02031869 -0.04063738 -0.06095608 -0.08127477]


# Backpropagation

In [ ]:
import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.5

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)

## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1-output)

# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:,None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)
